### ISSUE TITLE
Inconsistent output for QuantumSimulator vs SparseSimulator

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/qsharp-runtime#1081]
## Describe the bug
The same code produces different output when executed on QuantumSimulator vs SparseSimulator.
It appears that the basis states are labeled in little endian for QuantumSimulator, but for SparseSimulator they are sometimes labeled in big endian.

## To Reproduce

The following code:

```qsharp
use qs = Qubit[2] {
    H(qs[0]);
    Controlled Rx([qs[0]], (1.56, qs[1]));
    DumpMachine();
    ResetAll(qs);
}
```

produces this output on QuantumSimualtor (basis state |2⟩ has zero amplitude)

![image](https://user-images.githubusercontent.com/10113024/187044626-1bf3ef43-3d54-45e9-ae37-e1f87a0b2602.png)

but this output on SparseSimulator (basis state |1⟩ has zero amplitude)

![image](https://user-images.githubusercontent.com/10113024/187044617-ca2bccb9-59e8-4baa-9c89-c17886dfd100.png)

Oddly enough, for simpler examples (such as just applying an H gate to the first qubit without following it with Controlled Ry) the output of both simulators is the same.

## Expected behavior
I expect both simulators to have consistent output (up to omitting basis states with zero amplitude).

## System information
- OS: Windows 11
- .NET Core Version: 6.0.400
- QDK version: 0.24.201332, 0.25.222597

**Comment by DmitryVasilevsky** [comment]
Current numbering of qubits in the sparse simulator depends on the size of the state seen. For example, the following code
```
use qs = Qubit[10] {
    H(qs[0]);
    Message("Before:");
    DumpMachine();

    H(qs[8]);
    H(qs[8]);
    Message("After:");
    DumpMachine();

    ResetAll(qs);
}
```
Will result in the following output:
```
Before:
|0⟩      0.707107 +  0.000000 i  ==     **********           [ 0.500000 ]     --- [  0.00000 rad ]
|1⟩      0.707107 +  0.000000 i  ==     **********           [ 0.500000 ]     --- [  0.00000 rad ]
After:
|0⟩      0.707107 +  0.000000 i  ==     **********           [ 0.500000 ]     --- [  0.00000 rad ]
|256⟩    0.707107 +  0.000000 i  ==     **********           [ 0.500000 ]     --- [  0.00000 rad ]
```
I believe we want both sections to be the same. Investigating.

**Comment by DmitryVasilevsky** [comment]
Should be fixed after https://github.com/microsoft/qsharp-runtime/pull/1092

**Comment by weucode** [comment]
Here is another simple example illustrating the different behavior between QuantumSimulator and SparseSimulator. By the way, if using `DumpRegister` to show states of `qubits`, the result is right, which means that this behavior only occurred when outputs states of all qubits. Hope this example is helpful!

```
namespace NameSpace {
    open Microsoft.Quantum.Diagnostics;
    open Microsoft.Quantum.Intrinsic;


    @EntryPoint()
    operation main() : Unit {
        use qubits = Qubit[2];
        H(qubits[1]);
        DumpMachine();
        // DumpRegister((), qubits);
        ResetAll(qubits);        
    }
}
```
