### ISSUE TITLE
AccessViolationException after updating to .NET Core 3.1.100 Sdk

### ISSUE THREAD

**Issue by bettinaheim** [microsoft/qsharp-runtime#116]
## Describe the bug
When using the latest version of the .NET Core Sdk (3.1.100), the Borrow test in Microsoft.Quantum.Simulation.Simulators under CoreTests starts to not execute silently. The reason is a AccessViolationException. See the attached log from the build. 

## To Reproduce
Download and install the latest .NET Core Sdk from here: https://dotnet.microsoft.com/download. 
Try to run the Borrowing test. 

## Expected behavior
The test executes as it has with .NET Core Sdk 3.0.100. 

## Actual behavior
The test host process crashes due to a System.AccessViolationException (see attached log). 

## System information
- OS: Windows (not sure if the same problem exists on Mac/Linux)
- .NET Core Version:  3.1.100

For more details, see [Test log](https://github.com/microsoft/qsharp-runtime/files/4001654/8_Testing.Q.runtime.txt)

**Comment by bettinaheim** [comment]
@anpaz-msft @avasch01 For your awareness, since I am oof.

**Comment by bettinaheim** [comment]
Actually, come to think of it - our latest Binder issues might be related.

**Comment by avasch01** [comment]
The issue happens when we are trying to extract qubits from operation parameters:

2019-12-26T06:34:48.3736519Z The active test run was aborted. Reason: Test host process crashed : Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
2019-12-26T06:34:48.3737508Z    at Microsoft.Quantum.Tests.CoreOperations.BGen`1+In[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKey***=7cec85d7bea7798e]].Microsoft.Quantum.Simulation.Core.IApplyData.get_Qubits()
2019-12-26T06:34:48.3737760Z    at

**Comment by anpaz-msft** [comment]
There is some bug in .NET Core, probably in the compiler.

This causes an AccessViolation:
            System.Collections.Generic.IEnumerable<Qubit> IApplyData.Qubits
            {
                get
                {
                    var q2 = Data.Item2?.GetQubits();
                    return q2;
                }
            }

but this works file:


            System.Collections.Generic.IEnumerable<Qubit> IApplyData.Qubits
            {
                get
                {
                    var i2 = Data.Item2;
                    var q2 = i2?.GetQubits();
                    return q2;
                }
            }

Will try to reproduce this outside our code and log an issue with .NET Core.

**Comment by anpaz-msft** [comment]
Filed https://github.com/dotnet/core/issues/4045
There is a workaround that would require us to modify our codegen, but I'd rather just wait until this is confirmed (and fixed?) in .NET Core.

**Comment by bettinaheim** [comment]
> Filed https://github.com/dotnet/core/issues/4045
> There is a workaround that would require us to modify our codegen, but I'd rather just wait until this is confirmed (and fixed?) in .NET Core.

Given that this seems to be a fairly trivial modification to the code gen, I'd fix it rather sooner than later. For one, this is the current stable .NET Core version that people will download if they install .NEt Core, and I think it's a rather confusing error for people to run into. Second, it's a blocker for switching to the new Sdk setup, since there is a bug in the older .NET Core version we are currently using that interferes badly with our build.

**Comment by bettinaheim** [comment]
@anpaz-msft 
I've quickly looked into making the adaptions to generate the workaround. 
It looks like the workaround above is not sufficient, at least not what I understood it to be. 
Here is the code gen for the suggested workaround above: https://github.com/microsoft/qsharp-runtime/tree/beheim/workaround. 
It would be good if we could find a way around the issue on our end.

**Comment by bettinaheim** [comment]
> @anpaz-msft
> I've quickly looked into making the adaptions to generate the workaround.
> It looks like the workaround above is not sufficient, at least not what I understood it to be.
> Here is the code gen for the suggested workaround above: https://github.com/microsoft/qsharp-runtime/tree/beheim/workaround.
> It would be good if we could find a way around the issue on our end.

NVM, the build seems to have succeeded - I need to double check why it failed on my laptop, but I'll assume for now that I just didn't properly clean beforehand. Here's the PR: https://github.com/microsoft/qsharp-runtime/pull/120

**Comment by bettinaheim** [comment]
@anpaz-msft Since you reverted, please address this issue so we can use 3.1.

**Comment by bettinaheim** [comment]
I'll close this since we seem to have come to a consensus to drop support for 3.0 in favor of supporting 3.1. The current state is that we go with the work around of an additional assignment, which seems to work fine for 3.1.100 but now causes an AccessViolationException for 3.0.100. We should document this in our know issues.
