### ISSUE TITLE
Make printing stack trace optional and configurable

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/qsharp-runtime#156]
** Please describe what you would like the feature to accomplish.**
I'm updating the Quantum Katas to QDK version 0.10.2002.2610, and it looks like the cell output in case of an error became a lot bulkier. As of PR https://github.com/microsoft/qsharp-runtime/pull/79/, they include a mandatory Q# stack trace, which (for the use case of the Katas) doesn't really help the user figure out their issue, and might scare them away instead (this was the feedback we got when we had long stack trace in new Python tutorials).

![image](https://user-images.githubusercontent.com/10113024/75731034-6a3c9000-5ca3-11ea-90da-ecaa87b517db.png)

I considered turning off the test output, but that won't work, since the katas rely on the output of `Message` and `DumpMachine` for conveying useful information about the test outcomes (such as the first line of task 1.1) and for allowing the user to debug their solution. 

Ideally we would have an option to turn off the extra stack tracing, and then use that option in the `TestTarget` method of `TestSuiteRunner` in the katas.

**Comment by anpaz-msft** [comment]
I think #162 takes care of this, right @tcNickolas?

**Comment by tcNickolas** [comment]
I'm not sure about #162, #157 looks more relevant to it?

**Comment by bettinaheim** [comment]
@tcNickolas Could you confirm whether that is still relevant? If so, I'll assign it to an iteration shortly.

**Comment by tcNickolas** [comment]
This specific behavior in the Kata notebooks was fixed, yes. I'm not sure how configurable stack trace printing is now.

**Comment by DmitryVasilevsky** [comment]
@tcNickolas : SimulatorBase has public methods EnableExceptionPrinting() and DisableExceptionPrinting() which control printout in case of exception. Disabling exception printing will disable all exeption printing including words 'Unhandled exception.' and the message, I assume you want the message, but don't want stack trace. I can make printing of stack trace configurable.

**Comment by tcNickolas** [comment]
To provide a bit of background from the offline discussion: currently the Q# Jupyter notebooks do not print the exception stack trace, so I'm happy with their behavior.

However, the stack trace is still present in the katas when they are executed as Q# standalone projects; here is what the overall test output looks like:
![vs-stacktrace-screenshot](https://user-images.githubusercontent.com/10113024/106205018-b376b780-6172-11eb-9e17-997fe00175f6.jpg)

I'm trying to see how the output looks like when the tests are executed using `dotnet test`, as this is the way the katas are used from VS Code, but `dotnet test` doesn't work for me for some reason...

**Comment by tcNickolas** [comment]
Following an offline discussion, at this stage the error message is probably more confusing than the stack trace (in notebooks the stack trace came first so it was worse than in the VS environment). The problem is, some of the asserts that the Katas use don't allow to provide a custom message and print only the default message. Let me close this issue (since we agreed that we're not going to manipulate the stack trace) and open another one about error messages for asserts.

**Comment by cgranade** [comment]
@tcNickolas: That feature request is already being tracked at https://github.com/microsoft/QuantumLibraries/issues/219, if you'd be willing to chime in there. Thanks!

**Comment by DmitryVasilevsky** [comment]
One possible solution for projects:
https://github.com/microsoft/QuantumKatas/pull/596
