### ISSUE TITLE
Comments in src/Simulation/Simulators/QCTraceSimulator/Circuits/*.qs in XML format

### ISSUE THREAD

**Issue by anpaz-msft** [microsoft/qsharp-runtime#18]
These files have comments in XML-doc format. They should be moved to use Q# doc comments format (Markdown).

**Comment by codingupastorm** [comment]
Hey there,

I am interested in working on this. Do you have any requirements in terms of all of the inputs being documented, even if they're not in the old docs? 

I have started here:

https://github.com/microsoft/qsharp-runtime/compare/master...codingupastorm:master
