### ISSUE TITLE
opsCache prevents AbstractFactory.Register from performing override

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp-runtime#181]
https://github.com/microsoft/qsharp-runtime/blob/e6985b2f85cb0bc10d66e936f8c29419d2010a50/src/Simulation/Common/AbstractFactory.cs#L86-L89

**Comment by bettinaheim** [comment]
I believe this one was taken care of with https://github.com/microsoft/qsharp-runtime/pull/183.
