### ISSUE TITLE
Q# namespaces with the same fully-qualified name as a callable or type produce invalid C# code

### ISSUE THREAD

**Issue by samarsha** [microsoft/qsharp-runtime#245]
This program is accepted by the Q# compiler:

```
namespace Foo {
    function Bar() : Unit { }
}

namespace Foo.Bar {
    function Hello() : Unit { }
}
```

But it produces this C# compile error:

> obj\qsharp\src\Program.g.cs(26,26): error CS0101: The namespace "Foo" already contains a definition for "Bar".

**Comment by bettinaheim** [comment]
This is very closely relate to this one I believe: https://github.com/microsoft/qsharp-runtime/issues/46
It may make sense to track the two together.

**Comment by samarsha** [comment]
Yes, they're both related to flat Q# namespaces working incorrectly with nested C# namespaces. My instinct is to keep both of them separate since they have different error messages, but I'm OK with it if you want to combine them.

**Comment by swernli** [comment]
After reviewing this along with the work for #346 , it seems like it makes more sense to block this in the Q# compiler than try to handle it properly. I'm going to move this issue over to the compiler repo.

**Comment by swernli** [comment]
Closing in favor of compiler repo issue.
