### ISSUE TITLE
`NoOp<'T>` and IndexRange should be moved into the runtime repo as part of the language core.

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp-runtime#248]
Some of the rewrite steps in the qsharp-compiler repo have [a dependency](https://github.com/microsoft/qsharp-compiler/blob/851a8e3f6029ed7ae7da4c04d4e361152ffa5279/src/QsCompiler/Core/Dependencies.fs#L111) on a `NoOp` operation, which is currently defined both in the runtime repo ([here](https://github.com/microsoft/qsharp-runtime/blob/c8f23017800974814f19d8ef005fb9786cd734bb/src/Simulation/QsharpCore/ClassicalControl.qs#L8)) and in the Microsoft.Quantum.Canon library ([here](https://github.com/microsoft/QuantumLibraries/blob/e6885b1949f485c669a7eeebb2bd878af29d796c/Standard/src/Canon/NoOp.qs#L31)). This can cause problems during testing or execution if the `NoOp` call is inserted during a compilation where the libraries are not loaded. Other rewrite dependencies are defined in the runtime repo, many in the Microsoft.Quantum.Simulation.QuantumProcessor.Extensions namespace (rename pending) where the duplicate `NoOp` lives. 

To clean up this relationship, avoid dependency issues, and get rid of duplication, we should move the library implementation of `NoOp` into the runtime and make it part of the language core, similar to what was done for `MResetZ` and related measurement methods.

**Comment by swernli** [comment]
It looks like the [dependency list](https://github.com/microsoft/qsharp-compiler/blob/851a8e3f6029ed7ae7da4c04d4e361152ffa5279/src/QsCompiler/Core/Dependencies.fs#L216) in the compiler also includes `Microsoft.Quantum.Arrays.IndexRange` defined in the libraries. As part of the move of `NoOp` we should consider moving `IndexRange` at the same time. I'm narrowing down the intended usage in the code actions and will update this issue title and description once I have confirmed that approach.

**Comment by bettinaheim** [comment]
@cgranade I believe this is done?

**Comment by cgranade** [comment]
Yep, it is!
