### ISSUE TITLE
Random - Should this be zero-indexed?

### ISSUE THREAD

**Issue by christopherkang** [microsoft/qsharp-runtime#256]
**Describe the bug**
The 'Random' function is not zero indexed.

**To Reproduce**
Use Message($"{Random[1.0]}");

**Expected behavior**
If our arrays are zero-indexed, the returned index should (intuitively) be zero-indexed.

**Screenshots**

**System information**
 - OS: Windows 10
 - Version of affected NuGet or PyPI package or packages - Not sure

**Additional context**

**Comment by cgranade** [comment]
This should now be fixed, thanks again for the report @christopherkang!
