### ISSUE TITLE
Trace simulator outputs log of all quantum operations

### ISSUE THREAD

**Issue by christopherkang** [microsoft/qsharp-runtime#277]
** Please describe what you would like the feature to accomplish.**
Running some simulator returns a list of operations applied + where they are applied on the register. For example, outputting a log like this:

CNOT 0 1
H ? 1
X ? 0

** Describe the solution you'd like **
One potential is providing a field like willPrintOutput with a default value of False. 

** Describe alternatives you've considered **
Currently, one way to achieve this is by using `Message();` whenever an operation is called. But, this is pretty messy.

** Additional context **
N/A

**Comment by samarsha** [comment]
Hi @christopherkang! The simulator has [a few events](https://github.com/microsoft/qsharp-runtime/blob/master/src/Simulation/Common/SimulatorBase.cs#L24) related to this (unfortunately it doesn't look like they are documented). You could use `OnOperationStart`:

```csharp
using var simulator = new QuantumSimulator();
simulator.OnOperationStart += (operation, input) =>
    Console.WriteLine("{0} {1}", operation.Name, input.Value);
await HelloQ.Run(simulator);
```

That would output something like:

```
HelloQ ()
H q:0
CNOT (q:0, q:1)
X ([q:0], q:1)
```

Does this work for you?

**Comment by christopherkang** [comment]
That sounds fantastic! I'll go ahead and try it + open up a new issue if I have any problems. Thanks, @samarsha! 😄
