### ISSUE TITLE
QuantumProcessorDispatcher does not constrain its processor type

### ISSUE THREAD

**Issue by cgranade** [microsoft/qsharp-runtime#298]
## Describe the bug
The class `QuantumProcessorDispatcher` does not constrain the type of its quantum processor beyond `IQuantumProcessor`, such that subclasses of the `QuantumProcessorDispatcher` class cannot rely on being given a specific subtype of `IQuantumProcessor`. This in turn causes a reliance on unsafe runtime casting.

## To Reproduce
See sample code from https://github.com/microsoft/Quantum/pull/379:

```C#
    public partial class QpicSimulator : QuantumProcessorDispatcher {
        public QpicSimulator() : base(new QpicProcessor()) {}

        // Implementation of the `Barrier` operation for the QpicSimulator
        public class BarrierImpl : Barrier
        {
            private QpicProcessor processor;

            public BarrierImpl(QpicSimulator m) : base(m)
            {
                 // The type of the QuantumProcessor processor isn't known precisely here, requiring a cast.
                processor = (QpicProcessor)m.QuantumProcessor;
            }
        }
    }
```

## Proposed solution

Introduce a new class `QuantumProcessorDisatcher<T> where T : IQuantumProcessor` so that the exact type of `QuanutmProcessorDispatcher<T>.QuantumProcessor` can be expressed as `T`. This can be made as a non-breaking change by having `QuanutmProcessorDispatcher` inherit from `QuantumProcessorDispatcher<IQuantumProcessor>`.

**Comment by vadym-kl** [comment]
@cgranade, maybe you should use a slightly different terminology. The code below 
```csharp 
processor = (QpicProcessor)m.QuantumProcessor;
```
is safe in C#. If `m.QuantumProcessor` is not derived from `QpicProcessor`, an exception will be thrown at run-time telling the user that `m.QuantumProcessor` cannot be cast to `QpicProcessor`, which is a safe behavior. 

As a side remark, C# does support low-level unsafe casting in [System.Runtime.CompilerServices.Unsafe](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.unsafe?view=netcore-3.1), but it is not used
in the above example.

**Comment by bettinaheim** [comment]
@yusudz For your awareness, since we have had related conversations.

**Comment by bettinaheim** [comment]
@cgranade Since we will be deprecating these classes, I suggest to close this and leave it as is until they are removed.
