### ISSUE TITLE
Ability to generate a quantum circuit from a Q# opertaion.

### ISSUE THREAD

**Issue by anpaz** [microsoft/qsharp-runtime#31]
**Please describe what you would like the feature to accomplish.**
It would be great to be able to generate the quantum circuit diagram from a Q# operation.

**Describe the solution you'd like**
From the command line, provide the name of a Q# operation (define in a `.qs` file in the local folder) and generate a file that can be used to generate a the circuit diagram in ascii, png, pdf, or some other graphical format.

Extra points if this is integrated into IQ# so we can see the circuit inside a Jupyter Notebook.

**Additional context**
LiQUid used to be able to do this by generating the circuit into LaTeX. Another possibility is to generate this into qpic format.

**Comment by bettinaheim** [comment]
"Extra points if this is integrated into IQ# so we can see the circuit inside a Jupyter Notebook." 
I think this should be largely addressed by the new iqsharp functionality, so I'll close this one here. There are definitively further work that could be interesting (like LaTeX output), but I suggest to file a new concrete issue for these.

**Comment by msoeken** [comment]
Leaving a pointer to this [blog post](https://devblogs.microsoft.com/qsharp/build-your-own-q-simulator-part-3-a-circuit-diagram-builder-with-qpic/) that illustrates how to generate qpic output from Q# execution traces.

**Comment by fvirdia** [comment]
Hi, the blog post was very useful. In reference to it, I opened a new [issue](https://github.com/microsoft/Quantum/issues/462) asking if it's possible to add new features to it.
