### ISSUE TITLE
CSharpGeneration can't handle QsharpCompile of files with same filename

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp-runtime#357]
When using `QsharpCompile` in a csproj to explicitly pull in files not in the current folder tree, the resulting C# generated files will end up all in the same folder, namely `obj\qsharp\src\*.g.cs`. However, if two files in different folders have the same filename, such as `..\lib1\utils.qs` and `..\lib2\utils.qs` both try to generate to `obj\qsharp\src\utils.g.cs` and whichever is compiled second ends up overwriting the first, causing Not Found errors during C# compilation for anything expected to be generated from the first file.

I'm not really sure how to resolve this, as the behavior of preserving folder hierarchy for generated files doesn't make sense when considering files that are not in the same hierarchy. But if it can't be supported it should at least generate an explicit error instead of the cryptic side effects.

**Comment by ScottCarda-MS** [comment]
Fixed with #588.
