### ISSUE TITLE
Refactor EntryPointDriver to not compile against a specific simulator

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp-runtime#388]
Currently the `EntryPointDriver` is compiled against the default `QuantumSimulator` in a way that makes it necessary to create a new entry point driver project for each variant of the quantum simulator (like those built with different target packages). The entry point infrastructure already supports dynamically choosing an alternate simulator at runtime, so instead the explicit references to the default could be removed and the infrastructure reworked slightly to treat the built-in simulator the same was as a custom simulator, thus removing the linking between the two dlls and allowing any simulator variant to be used with the single entry point driver.

See #249 for the original context of this ask.

**Comment by filipw** [comment]
yes please 👏

**Comment by swernli** [comment]
After finishing the infrastructure for #249, we now compile the simulators without a direct dependency on a specific target package; that is to say, the `Microsoft.Quantum.Simulators` package no longer depends on `Microsoft.Quantum.QSharp.Core` nor does it assume the presence of a specific Q# intrinsic gate set. That should allow any simulator using any gate set to be built along with the entry point or loaded dynamically without requiring that simulator to use the QSharp.Core target package.
