### ISSUE TITLE
Add Improvement Request Template

### ISSUE THREAD

**Issue by kuzminrobin** [microsoft/qsharp-runtime#483]
On [this page](https://github.com/microsoft/qsharp-runtime/issues/new/choose) add a new template - **Improvement Request**, in order to file the requests for improvement. E.g. [coding style improvement](https://github.com/microsoft/qsharp-runtime/issues/482).
Add a new .md file [here](https://github.com/microsoft/qsharp-runtime/tree/main/.github/ISSUE_TEMPLATE).

**Comment by bettinaheim** [comment]
@kuzminrobin Sounds like a good idea. Do you want to go ahead and do this?

**Comment by kuzminrobin** [comment]
Why not? I'm putting this to my list and assigning to myself.
