### ISSUE TITLE
C# code generation fails for UDTs with named items called `Item*`.

### ISSUE THREAD

**Issue by cgranade** [microsoft/qsharp-runtime#50]
## Describe the bug
I will readily admit that no one should ever write this code, but if one defines a UDT with named items such as `Item1` and `Item2`, compiling the generated C# code fails. In particular, compilation fails even if the affected UDT is never actually used.

## To Reproduce
```Q#
newtype Evil = (
    Item2: Int,
    Item1: String
);
```

![image](https://user-images.githubusercontent.com/31516/64047315-472df980-cb23-11e9-8511-5bf9d788d3b9.png)

**Comment by anpaz-msft** [comment]
We automatically generate the `Item1`, `Item2`, etc, fields for UDTs, but I don't they are really used as all assignments happen via de-construction, so we might be able to just remove the fields.
