### ISSUE TITLE
UnitTests.csproj should be split into separate projects by execution target

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp-runtime#502]
Currently the [UnitTests.csproj](https://github.com/microsoft/qsharp-runtime/blob/main/src/Simulation/Simulators.Tests/TestProjects/UnitTests/UnitTests.csproj) includes dependent projects that have different execution targets, namely HoneywellExe.csproj, IonQExe.csproj, and QCIExe.csproj. Pulling in projects with different execution targets as part of a single compilation can cause failures due to collisions, as we found when updating `body instrinsic` math functions to be concrete Q# implementations (see https://github.com/microsoft/qsharp-runtime/pull/497#issuecomment-773728087). To resolve this, these projects should be split out into independent unit tests so that it's always zero or one execution target in any given compilation.

**Comment by cgranade** [comment]
Thanks for figuring this one out, @swernli! Once this split is finished, I'll go on and make `PI` pure-Q# again. Thank you!

**Comment by swernli** [comment]
Happy to help, @cgranade ! I went ahead and made `PI` pure Q# again as part of the fix, so we should be good to go.

**Comment by cgranade** [comment]
Awesome, thanks for the update on that!
