### ISSUE TITLE
We need a better way to update the package versions across the repo

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp-runtime#530]
Several times when working on a change that needs to bring in new features from an updated QDK, the developer needs to update the package versions of the Microsoft.Quantum.Sdk (and any other explicitly referenced packages) across the whole repo. This can lead to missed update locations, mismatched packages, and subtle build failures. Rather than doing this by hand, we should consider either a helper script that updates the whole repo to a single provided QDK version or a single common location for defining the current QDK version to use across all projects.

For inspiration, we could draw from the script in the katas repo: https://github.com/microsoft/QuantumKatas/blob/main/scripts/Update-QDKVersion.ps1

**Comment by swernli** [comment]
See https://github.com/microsoft/qsharp-runtime/pull/529/commits/48790b13bc5a3238a0b4347c116004dd68076991 as an example showing all the places that need to be updated each time...

FYI @kuzminrobin , @samarsha

**Comment by cgranade** [comment]
Perhaps this would be good to include in more general discussions of a PowerShell module with build tooling for the QDK?

**Comment by swernli** [comment]
@cgranade That’s a good point. It was also brought up that we may be able to minimize the hassle by using some kind of variable in place of the version, and then putting a single version string in a common props file. I should update the title to reflect the idea that we need a solution to the problem but not specifically tie it to a script that gets executed.

**Comment by swernli** [comment]
Reopening so that we don't lose track of one other location that has the version number: [Microsoft.Quantum.CSharpGeneration.fsproj](https://github.com/microsoft/qsharp-runtime/blob/main/src/Simulation/CSharpGeneration/Microsoft.Quantum.CSharpGeneration.fsproj#L25) uses an explicit reference to the compiler package. The fix in #614 simplifies the issue from twenty-something places that need to updated into just two places, but this fsproj could still cause confusion for people. Is there any way we can piggy back off the global.json to set the compiler package version as well?

**Comment by swernli** [comment]
After further discussion, it seems like it makes more sense to close this current issue and pursue moving CSharpGeneration rewrite step into the qsharp-compiler repo instead.
