### ISSUE TITLE
QIR simulator should check result of qubit Release

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp-runtime#552]
Our existing C# wrapper for the fullstate simulator checks the result of `release` on a qubit to ensure that the qubit was in a well-known state at release time (see #206 for the detailed discussion of the release semantics). Releasing a qubit that could be entangled can result in problems for the rest of the program, and the simulator gives developers a way to use Q# to validate their algorithms for this. The C++ wrapper around the simulator used in QIR does not check the return of `release` and therefore doesn't provide this feedback, allowing for algorithms to effectively leak state.

To test this, consider the following Q#:
```qsharp
operation Test() : Unit {
    use q = Qubit();
    X(q);
}
```
Because the qubit is not in the ground state and hasn't been measured, running this code on the C# simulator will result in a `ReleasedQubitsAreNotInZeroState` exception being thrown from [QubitManager.cs](https://github.com/microsoft/qsharp-runtime/blob/main/src/Simulation/Simulators/QuantumSimulator/QubitManager.cs#L59). We need an equivalent check in the QIR fullstate simulator wrapper.

@bettinaheim @cgranade FYI

**Comment by bettinaheim** [comment]
@swernli I believe you are already looking into this one, so I'll assign it to you.
