### ISSUE TITLE
Consider removing `src/QirRuntime/externals/LLVM`

### ISSUE THREAD

**Issue by kuzminrobin** [microsoft/qsharp-runtime#554]
(Technical Debt)
Make sure that the info about `llvm-ar.exe` in [here](https://github.com/microsoft/qsharp-runtime/blob/main/src/QirRuntime/externals/readme.md#llvm-tools) is still applicable. If not then consider 
* removing [`src/QirRuntime/externals/LLVM`](https://github.com/microsoft/qsharp-runtime/tree/main/src/QirRuntime/externals/LLVM) 
* removing the `$llvmExtras` from [qsharp-runtime/src/QirRuntime/build-qir-runtime.ps1](https://github.com/microsoft/qsharp-runtime/blob/main/src/QirRuntime/build-qir-runtime.ps1)
* Using the `llvm-ar.exe` from the (in `PATH`) clang/llvm toolchain installation, e.g. at 
`C:\Program Files\LLVM\bin` or 
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\Llvm\x64\bin`.

**Comment by bettinaheim** [comment]
@cesarcz @swernli Do you have any insights into whether the latest updates or updates in the near future make this obsolete?

**Comment by swernli** [comment]
@bettinaheim I created https://github.com/microsoft/qsharp-runtime/pull/556 to remove this, let's see if the pipeline is satisfied. I don't have a local Windows setup for QIR development (I've been using a Linux container) so I'm not 100% sure if this will work, but I don't see any place where we still use this in our cmake files, so hopefully it should just work (famous last words ;)).
