### ISSUE TITLE
AssertMeasurementProbability() Doc is missing some info.

### ISSUE THREAD

**Issue by kuzminrobin** [microsoft/qsharp-runtime#613]
[This fragment](https://github.com/microsoft/qsharp-runtime/blob/3c8a96eeec5e4cee33f0b376710327f02069e90e/src/Simulation/QSharpFoundation/Diagnostics/Assert.qs#L48) is missing the info about the last param - `tol` (possible text is [here](https://github.com/microsoft/qsharp-runtime/blob/3c8a96eeec5e4cee33f0b376710327f02069e90e/src/Simulation/QSharpFoundation/Diagnostics/AssertQubit.qs#L39)).
This likely affects the same missing info [here](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.diagnostics.assertmeasurementprobability#tol--double).

To be fixed together with the QIR Runtime implementation of 
* operation AssertMeasurement(bases : Pauli[], qubits : Qubit[], result : Result, msg : String) : Unit is Adj + Ctl
* operation AssertMeasurementProbability(bases : Pauli[], qubits : Qubit[], result : Result, prob : Double, msg : String, tol : Double) : Unit is Adj + Ctl

---
Also make the fragment `Measure(bases, qubits)` a link to [Measure()](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.intrinsic.measure), otherwise it is not that fast to find Measure() page.

**Comment by cgranade** [comment]
Agreed, it looks like that input is not documented.

One of the recent improvements made in the documentation generation tool is to raise warnings about undocumented inputs such as this; we should check that this warning is correctly emitted when compiling the runtime repo.

**Comment by bettinaheim** [comment]
Related (if only by which part of the generated docs are impacted): https://github.com/microsoft/qsharp-compiler/issues/949.

**Comment by cgranade** [comment]
The root cause for this one may be different, in that the original comment being interpreted by the docgen tool is indeed missing a `/// ## tol` section:

https://github.com/microsoft/qsharp-runtime/blob/974a385cc57c2b663e8134c1f3170f9cb8ae5fb1/src/Simulation/QSharpFoundation/Diagnostics/Assert.qs#L47

Ideally, this should raise a warning, but I don't see it amongst the 36 documentation generation warnings raised in the latest e2e build...
