### ISSUE TITLE
Error messaging in AssertProb

### ISSUE THREAD

**Issue by bettinaheim** [microsoft/qsharp-runtime#65]
The probability given as the actual probability in the error message of AssertProb is not the same as the one given as argument, which may be slightly confusing. This is the offending line: https://github.com/microsoft/qsharp-runtime/blob/ebb4b2a9de0110ab45a6e38b38cfbd664759483f/src/Simulation/Simulators/QuantumSimulator/AssertProb.cs#L49

**Comment by adrianwyatt** [comment]
looking at this now

**Comment by adrianwyatt** [comment]
Fix submitted. #78

**Comment by bettinaheim** [comment]
Thanks, @adrianwyatt!
