### ISSUE TITLE
Unhandled exception when running the resources estimator

### ISSUE THREAD

**Issue by geduardo** [microsoft/qsharp-runtime#655]
## Describe the bug
When I try to run the resources estimator I get an unhandled exception:

> Unhandled exception. System.InvalidOperationException: Sequence contains no elements
>    at System.Linq.ThrowHelper.ThrowNoElementsException()
>    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
>    at Microsoft.Quantum.Simulation.Simulators.QCTraceSimulators.Implementation.QCTraceSimulatorImpl.RegisterPrimitiveOperationsGivenAsCircuits(Assembly coreAssembly)   at Microsoft.Quantum.Simulation.Simulators.QCTraceSimulators.Implementation.QCTraceSimulatorImpl..ctor(QCTraceSimulatorConfiguration config, Assembly coreAssembly)
>    at Microsoft.Quantum.Simulation.Simulators.QCTraceSimulators.QCTraceSimulator..ctor(QCTraceSimulatorConfiguration config, Assembly coreAssembly)
>    at Microsoft.Quantum.Simulation.Simulators.ResourcesEstimator..ctor(QCTraceSimulatorConfiguration config)
>    at Microsoft.Quantum.Simulation.Simulators.ResourcesEstimator..ctor()
>    at Namespace.Program.Main(String[] args) in C:\Users\v-edsanc\Desktop\resest\host\Program.cs:line 10
> 

## To Reproduce
Steps to reproduce the behavior. 
Please provide a code sample for your issue if it is relevant, either inline, link to a gist (or similar) or add it as a zipped attachment.

C# driver:

```
using System;
using Microsoft.Quantum.Simulation.Simulators;

namespace Namespace
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var sim = new ResourcesEstimator();

            OperationExample.Run(sim).Wait();
            Console.WriteLine(sim.ToTSV());
        }
    }
}
```

Q# code:

```
 namespace Namespace {
  open Microsoft.Quantum.Intrinsic;
  open Microsoft.Quantum.Canon;

  operation OperationExample() : Unit {
    use (a, b) = (Qubit(), Qubit());
    CNOT(a, b);
  }
}
```

## Expected behavior
Correct estimation of the resources of the operation.

## System information
- OS: Windows 10

- .NET Core Version: 5.0.202

**Comment by dime10** [comment]
I could not reproduce this using .NET core 3.1, maybe an issue with version 5.0.

**Comment by geduardo** [comment]
@dime10 great, changing to 3.1 solved the issue.

Thanks!
