### ISSUE TITLE
Provide Q# call stack information with source locations in case Q# program fails

### ISSUE THREAD

**Issue by vadym-kl** [microsoft/qsharp-runtime#70]
## Please describe what you would like the feature to accomplish.
Currently it is hard to interpret C# call-stack to recover corresponding Q# call stack.
It would be nice no see method `EnableCallStackTracking()` added to `SimulatorBase` class and 
`CallStack` property. The method would enable tracking of the call-stack and the property will give access to the Q# call stack at the point when the first failure in Q# program has happened. 

## Describe the solution you'd like 
Proposed solution should use combination of `OnOperationStart`, `OnOperationEnd` and `OnFail` events, #68 and C# call stack information to reconstruct Q# call-stack together with corresponding source locations. 

## Additional context
This will be very helpful for IQ# error handling and error reporting.
This uses on #58.

**Comment by bettinaheim** [comment]
Done.
