### ISSUE TITLE
QIR runtime heap alloc and heap free functions should be removed

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp-runtime#702]
The QIR runtime currently includes functions for allocating and freeing memory from the heap:
https://github.com/microsoft/qsharp-runtime/blob/380003f44cea08ae0b91132ad168ea34ba56297d/src/Qir/Runtime/lib/QIR/bridge-rt.ll#L124
https://github.com/microsoft/qsharp-runtime/blob/380003f44cea08ae0b91132ad168ea34ba56297d/src/Qir/Runtime/lib/QIR/bridge-rt.ll#L129

These two methods are neither part of the QIR specification, nor are they used anywhere in the runtime implementation or in QIR generation, making them dead code. If we expect them to be needed in the future then we should update the QIR spec to describe their intended use, otherwise we should remove them and the underlying support to avoid the cost of maintaining them.

@bettinaheim @alan-geller @kuzminrobin FYI.

**Comment by Patil2099** [comment]
I would love to work on it. @swernli.

**Comment by swernli** [comment]
Thanks @Patil2099! Always happy to see involvement from the community! Just as a heads up, we may end up deciding to keep the functions, depending on feedback from the rest of the team on whether removal is the right way to go. I'll follow up on the PR with feedback there, and if the issue is triaged and accepted we can use your PR to resolve it.

**Comment by swernli** [comment]
Sounds like we have consensus that this is a good removal to make. Removing `needs triage` label.
