### ISSUE TITLE
Autosubstitution depends on packages pulled in by default by the Microsoft.Quantum.Sdk

### ISSUE THREAD

**Issue by anpaz** [microsoft/qsharp-runtime#741]
## Describe the bug
To keep repo dependencies clean, no packages in qsharp-runtime can have dependencies on QuantumLibraries, as the dependencies need to flow just one way. 

By default, though, the Microsoft.Quantum.Sdk adds dependencies to Standard unless turned off by the 
`IncludeQSharpCorePackages` property, so this property is required in all projects on the qsharp-runtime repo.

## To Reproduce
Check the package dependencies in either VS or nuget, and check that Standard is marked as dependency.

**Comment by guenp** [comment]
Related PR: https://github.com/microsoft/qsharp-runtime/pull/742

**Comment by bettinaheim** [comment]
The fact that it also depends on the C# generation that is pulled in by the Sdk may cause the rewrite step to not load properly as part of the added tests as well.

**Comment by bettinaheim** [comment]
Addressed with https://github.com/microsoft/qsharp-runtime/pull/748.
