### ISSUE TITLE
QIR Validation on Numerics Samples Stalls and Consumes Resources

### ISSUE THREAD

**Issue by ScottCarda-MS** [microsoft/qsharp-runtime#757]
## Describe the bug
When running the executables produced by the qir-cli tool when used on the numerics\EvaluatingFunctions and the numerics\ResourceCounting samples from the Quantum samples repo, the executables run forever (stall) and also use an enormous amount of system resources (~54 GB of RAM).

## To Reproduce
- Download the Microsoft.Quantum.Qir.CommandLineTool version: 0.18.210628522-alpha from here: https://dev.azure.com/ms-quantum-public/Microsoft%20Quantum%20(public)/_build/results?buildId=28522&view=artifacts&pathAsName=false&type=publishedArtifacts
  - It is under Artifacts\drop\drops\internal_tools
- Install the tool by placing it in a local NuGet source and run the command `dotnet tool install Microsoft.Quantum.Qir.CommandLineTool -g --version 0.18.210628522-alpha`
- Copy or clone the latest from the main branch of the Quantum repo: https://github.com/Microsoft/Quantum
- Build the QuantumSamples\samples\numerics\EvaluatingFunctions and C:\Repos\QuantumSamples\samples\numerics\ResourceCounting samples buy running `dotnet build <ProjectFile>.csproj /property:QirGeneration="true"` (remember to replace \<ProjectFile\> as appropriate).
- From the project folder locations, build the executable with `qir-cli --dll .\bin\Debug\netcoreapp3.1\<ProjectName>.dll --exe qir` (replace \<ProjectName\>).
- Now run the resulting executables found in the .\qir\ subfolders of the project folders for EvaluatingFunctions and ResourceCounting samples to see that they both have the described issue.

## Expected behavior
Until recently (QDK version 0.16.2105140472 works fine) these samples worked without consuming large amounts of system resources and actually completed in a short amount of time, when run using the qir-cli tool.

## System information
- QDK version: 0.18.2106148911
- Microsoft.Quantum.Qir.CommandLineTool version: 0.18.210628522-alpha

**Comment by bettinaheim** [comment]
The two samples are written to illustrate the resource counting and correspondingly use a lot more qubits than can be simulator on the full state simulator (300+). The behavior is hence expected.
