### ISSUE TITLE
Fullstate simulator library should not be renamed to Winodws-style dll on non-Windows platforms.

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp-runtime#783]
Right now logic exists in our build passes that takes the output from the xplat build of the native simulator and renames all the files into the Windows style, `Microsoft.Quantum.Simulator.Runtime.dll`. This is unnecessary and causes confusion when working on other platforms. We should remove this rename, and then update the .csproj files in this repo such that local development does not take a dependency on the rename happening. For example, this part of Simulators.Dev.props:
https://github.com/microsoft/qsharp-runtime/blob/4f32b5bbd6d3217e21033f04cdd47f02581fba14/src/Simulation/Common/Simulators.Dev.props#L26-L32
Should be updated to not expect the file with the Windows specific naming and instead use the built-in support .NET has for dynamically loading the right platform specific library.

**Comment by bettinaheim** [comment]
@cesarzc I believe this is what you have been looking into related to the runtime package in any case.
