### ISSUE TITLE
Enable setting breakpoints on Q# code in  Visual Studio Code 

### ISSUE THREAD

**Issue by vadym-kl** [microsoft/qsharp-runtime#80]
## Please describe what you would like the feature to accomplish.
Enable setting breakpoints on Q# code in  Visual Studio Code similar to Visual Studio.

## Describe the solution you'd like 
The solution requires contribution to [C# extension](https://github.com/OmniSharp/omnisharp-vscode.git) for Visual Studio Code. 
Creating issue here for visibility and for making sure that a workaround is well known. 

## Describe alternatives you've considered 
There is a known workaround that requires adding one line to `package.json` of  [C# extension](https://github.com/OmniSharp/omnisharp-vscode.git). 
Steps are the following:
- Run `code ~/.vscode/extensions/ms-vscode.csharp-*/package.json` in Bash
- Goto symbol `enableBreakpointsFor` in `package.json` ( type `Ctrl+P` `@enableBreakpointsFor` )
- Add `qsharp` to the list of `languageIds`:
````json
...
"type": "coreclr",
"label": ".NET Core",
"enableBreakpointsFor": {
	"languageIds": [
		"csharp",
		"razor",
		"qsharp",
		"aspnetcorerazor"
	]
},
...
````

**Comment by bettinaheim** [comment]
Let's see what they say: https://github.com/OmniSharp/omnisharp-vscode/pull/3417

**Comment by bettinaheim** [comment]
Good news! :)
