### ISSUE TITLE
Provide QIR runtime binaries as a part of QDK Nuget 

### ISSUE THREAD

**Issue by vadym-kl** [microsoft/qsharp-runtime#954]
**Please describe what you would like the feature to accomplish.**  
Currently, if a user wants to build QIR generated by Q# compiler they they need to do two following  steps: 

* Find commit version of QIR Runtime that corresponds to given release of Q# compiler 
* Build QIR Runtime from given commit 

Shipping QIR runtime binaries will help user avoid above steps.

**Describe the solution you'd like**  
I would like to have pre-build binaries for QIR Runtime for Mac, Linux and Windows to be available as part of a Nuget  packages. 
Ideally, I would like those binaries to appear beside QIR files generated by Q# compilers, when `dotnet build /property:QirGeneration=true` is called. 

**Describe alternatives you've considered**  
Existing alternative solution is described here https://github.com/microsoft/qsharp-runtime/issues/865. 

**Additional context** 
Currently it is quite difficult to build QIR code generated by Q# compiler. 
For details see steps here: 
https://github.com/microsoft/qsharp-runtime/issues/865

**Comment by swernli** [comment]
@vadym-kl the package you are looking for is https://www.nuget.org/packages/Microsoft.Quantum.Qir.Runtime/. It contains native binaries for Mac, Linux, and Windows along with header files inside of the `runtimes` folder of the nuget package.
