### ISSUE TITLE
`Microsoft.Quantum.Core.Default` should be marked as deprecated and then removed

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp-runtime#975]
Likely a prerequisite: https://github.com/microsoft/QuantumLibraries/issues/546

The `Default` function uses the deprecated and unsafe array creation syntax, and should not be supported any longer. We should mark the function as deprecated as well and prepare to remove it. This may require revisiting the libraries to ensure all remaining uses of it are removed as well.

Related: https://github.com/microsoft/qsharp-runtime/issues/977

**Comment by msoeken** [comment]
I want to bring attention to @cgranade's comment https://github.com/microsoft/QuantumLibraries/pull/553#discussion_r845271159 in microsoft/QuantumLibraries#553. We have often used `Default` to initialize UDTs by partially or completely assigning UDT fields with the `w/` syntax. Maybe it's worth to discuss an alternative to this paradigm as part of this issue.

**Comment by samarsha** [comment]
Instead of `Default<MyUdt>() w/ Field <- foo`, you can use `DefaultMyUdt() w/ ItemName <- foo` by defining your own function:

```qsharp
function DefaultMyUdt() : MyUdt {
    return MyUdt(field1, field2, field3);
}
```
