### ISSUE TITLE
An issue about the Parity function

### ISSUE THREAD

**Issue by QuXing9** [microsoft/qsharp-runtime#993]
## Description

Hello! When executing the following testcase, the program throws an exception. It seems that the value of argument `a` should not be less than `0`. But the [document](https://docs.microsoft.com/zh-cn/qsharp/api/qsharp/microsoft.quantum.bitwise.parity) doesn't state this condition. 

## Testcase

~~~c#
namespace NISLNameSpace {
	open Microsoft.Quantum.Intrinsic;
	open Microsoft.Quantum.Bitwise;

	@EntryPoint()
	operation main() : Unit {
		Message($"{Parity(-1)}");
	}
}
~~~

## Actual Behavior

~~~c#
Unhandled exception. System.OverflowException: Value was either too large or too small for a UInt64.
 ---> NISLNameSpace.main on E:\GithubProjects\QuantumFuzzing\src\Fuzzing\qsharpPattern\Program.qs:line 7
~~~

## Expected Behavior

show the range of argument `a` in the document

## Environment

`Operating system`: Windows 10

`dotnet version`: 3.1.414

`QDK`: 0.24.201332

## Command

dotnet run

**Comment by bettinaheim** [comment]
Thanks for reporting. 

The function System.Convert.ToUInt64 used [here](https://github.com/microsoft/qsharp-runtime/blob/21f5fab97682d9bc0ae8e3b58f679fdb952f1c24/src/Simulation/QSharpFoundation/Bitwise/Bitwise.cs#L52) is documented to throw if the give value is less than 0 (see [docs](https://docs.microsoft.com/en-us/dotnet/api/system.convert.touint64?view=net-6.0#system-convert-touint64)). We can either document that the value needs to be positive or fix the code to allow negative values. Requiring that the value is positive might be less ambiguous.

**Comment by kuzminrobin** [comment]
Does not repro with the QIR Runtime, and with QIR RT we have a [test](https://github.com/microsoft/qsharp-runtime/blob/f76ca96d38e4c32e1cedc0ea02b3846be1f1379c/src/Qir/Tests/QIR-static/qsharp/qir-test-other.qs#L46) for that case.
I was able to repro locally with the C# Runtime. I will work on the fix later.
